### ISSUE TITLE
Info about glTF Blender addon

### ISSUE THREAD

**Issue by julienduroure** [Soft8Soft/verge3d-blender-addon#2]
Hello,
For info: 
The Khronos Exporter addon is no more in active development, and is replaced by a Khronos importer/exporter.
The new repo is: https://github.com/KhronosGroup/glTF-Blender-IO
and is built by default in Blender 2.8

**Comment by alexkowel** [comment]
Hi Julien. Thanks for the heads up and for your awesome glTF add-on! We're going to support both Verge3D-specific and the generic glTF exporter in our engine loader.
